apiVersion: v2
name: mapproxy
description: A Helm chart for mapproxy service
type: application
version: 6.0.1
appVersion: 6.0.1
dependencies:
- name: nginx
  version: 2.1.5
  repository: oci://acrarolibotnonprod.azurecr.io/helm/common

- name: mclabels
  version: 1.0.1
  repository: oci://acrarolibotnonprod.azurecr.io/helm/infra
