[uwsgi]
{{- $metrics := (include "common.metrics.merged" .) | fromYaml }}
; based on https://github.com/kartoza/docker-mapproxy/blob/master/build_data/uwsgi.ini
chdir = /mapproxy
wsgi-file = app.py
callable = application
; attention  do not change - its releated to volumesMount configuration and mapproxinator
master-fifo = /uwsgi_config/fifo0
pidfile=/tmp/mapproxy.pid
socket = :{{ .Values.mapproxy.uwsgi.socket }}
http-socket = :{{ .Values.mapproxy.uwsgi.httpSocket }}
processes = {{ .Values.mapproxy.uwsgi.processes }} ; Maximum number of workers allowed
threads = {{ .Values.mapproxy.uwsgi.threads }}
Enable-threads = true
master = true
lazy-app = true                      ; Fork workers after app load (required for OTel)
py-callos-afterfork = true           ; allow workers to trap signals
cheaper = 2                          ; Minimum number of workers allowed
disable-logging = {{ .Values.mapproxy.uwsgi.disableLogging }}
log-5xx = true
log-4xx = true
log-drain = GET /metrics
memory-report = true
log-master = true
vacuum = true
die-on-term = true                   ; Shutdown when receiving SIGTERM (default is respawn)
need-app = true                      ; This parameter prevents uWSGI from starting if it is unable to find or load your application module
max-requests = 1000                  ; Restart workers after this many requests
reload-on-rss = 2048                 ; Restart workers after this much resident memory
buffer-size = 14336                  ; 14K, Set the internal buffer size for uwsgi packet parsing. Default is 4k.
worker-reload-mercy = 60             ; How long to wait before forcefully killing workers
wsgi-disable-file-wrapper = true
harakiri = {{ .Values.mapproxy.uwsgi.harakiri }}
chmod-socket = 664
{{ if $metrics.enabled }}
stats = :{{ .Values.mapproxy.uwsgi.statsServer.stats }}
stats-http = true
stats-min = {{ .Values.mapproxy.uwsgi.statsServer.statsMinify }}
{{ end }}